// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Prisma CLI commands (migrate, db push, studio) run through this
  // datasource. DIRECT_URL (non-pooled) is used here because Supabase's
  // pgbouncer pooler doesn't support the prepared statements schema
  // migrations need. The app itself connects with the pooled
  // DATABASE_URL at runtime — see lib/prisma.ts.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
